#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=(realpath $1) 
else
    selected=$(find ~ ~/personal ~/college ~/college/430-strategy ~/college/482-capstone ~/college/438-distributed -mindepth 1 -maxdepth 1 -type d | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selectedName=$(basename "$selected" | tr . _)
tmuxRunning=$(pgrep tmux)

# not running
if [[ -z $tmuxRunning ]]; then
    tmux new-session -s $selectedName -c $selected
    exit 0
fi

# TODO: detached
# "unexpected OEF" may have been due to missing `fi`
# --> try this again; attach, then switch client or start new session
#if [[ -z $TMUX ]]; then
#    tmux attach
#fi

# attached
if ! tmux has-session -t=$selectedName 2> /dev/null; then
    tmux new-session -ds $selectedName -c $selected
fi

tmux switch-client -t $selectedName

