#!/usr/bin/env bash

log() {
    echo "$*" >> $HOME/.local/scripts/todo-finder_log
}

todo=$(find $PWD -maxdepth 1 -iname 'todo.md' -print -quit)

if [[ -n $todo ]]; then
    nvim "$todo"
    exit 0
fi

DIRS=(
    $HOME/personal
    $HOME/school
    $HOME/work
)

selected=$(
    printf "%s\n" "${DIRS[@]}" \
    | sed "s|^$HOME/||" \
    | fzf --layout=reverse
)

if [[ -z $selected ]]; then
    exit 0
fi

nvim $HOME/"$selected"/todo.md
